// <auto-generated />
using System;
using BehrendTutors.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BehrendTutors.Migrations
{
    [DbContext(typeof(BehrendTutorsContext))]
    [Migration("20240115234527_FixNamingPls")]
    partial class FixNamingPls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BehrendTutors.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("BehrendTutors.Models.Class", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ClassNum")
                        .HasColumnType("int");

                    b.Property<string>("ClassTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseNum")
                        .HasColumnType("int");

                    b.Property<int>("SectionNum")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("BehrendTutors.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tutor");
                });

            modelBuilder.Entity("BehrendTutors.Models.TutorClass", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("TutorId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("TutorClass");
                });

            modelBuilder.Entity("BehrendTutors.Models.TutorSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Classid")
                        .HasColumnType("int");

                    b.Property<DateTime>("SessionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId1")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Classid");

                    b.HasIndex("TutorId1");

                    b.ToTable("TutorSession");
                });

            modelBuilder.Entity("BehrendTutors.Models.TutorClass", b =>
                {
                    b.HasOne("BehrendTutors.Models.Class", "Class")
                        .WithMany("TutorClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BehrendTutors.Models.Tutor", "Tutor")
                        .WithMany("TutorClasses")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BehrendTutors.Models.TutorSession", b =>
                {
                    b.HasOne("BehrendTutors.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("Classid");

                    b.HasOne("BehrendTutors.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId1");

                    b.Navigation("Class");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BehrendTutors.Models.Class", b =>
                {
                    b.Navigation("TutorClasses");
                });

            modelBuilder.Entity("BehrendTutors.Models.Tutor", b =>
                {
                    b.Navigation("TutorClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
